name: StreamingAir
description: "StreamingAir."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  # Rimosso dio: ^5.3.2 (usato solo per il download)
  path_provider: ^2.1.1 # Ancora usato per altre funzionalità
  permission_handler: ^11.0.0 # Necessario per altre funzionalità
  share_plus: ^7.0.0 # Usato altrove nell'app
  package_info_plus: ^4.0.0

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
